[project]
name = "factory"
version = "0.1.0"
description = "A simple processing skeleton using ray actors"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ray>=2.36.1",
    "torch>=2.7.1",
]
